### PR TITLE
Adding support for transforming bensampo/laravel-enum enums

### PR DESCRIPTION
**Pull request by badams**
Adding support for transforming (BenSampo/laravel-enum)[https://github.com/BenSampo/laravel-enum] based Enums, this implementation was based on the `MyclabsEnumTransformer` with some minor difference to the outputted format.

### CODE REVIEW

**Comment by rubenvanassche** [comment]
I'm not sure if we want to add this to the main package, because with that philosophy we could add a thousand enum packages which all need to be maintained. We included the myclabs en Spatie enums because we're using them in our own projects.

But I like the idea of having a lot of transformers available, so could you put this transformer into your own package? I'll add a section in the docs with a link to your package so everyone can find it quite easily.

**Comment by badams** [comment]
Thanks @rubenvanassche  I wondered if that might be the case, will create my own package 👍

**Comment by rubenvanassche** [comment]
Looking forward to it!

**Comment by badams** [comment]
> Looking forward to it!

@rubenvanassche I've setup the package here if you want to add it to the docs https://github.com/wt-health/laravel-enum-transformer 

Cheers

**Comment by rubenvanassche** [comment]
Thanks @badams, added it to the docs!

**Pull request closed without merging**
